---
title: "Gallery"
description: |
  A selection of the plots I made for #TidyTuesday. Find the whole list
  [here](https://github.com/etiennebacher/tidytuesday).
output:
  distill::distill_article
base_url: https://www.etiennebacher.com/
---

```{r echo = FALSE}
knitr::opts_chunk$set(
  echo = FALSE
)
```


<head>

<link type="text/css" rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/lightgallery/1.6.0/css/lightgallery.min.css" /> 
<script src="https://cdnjs.cloudflare.com/ajax/libs/lightgallery-js/1.4.1-beta.0/js/lightgallery.min.js"></script>

<!-- lightgallery plugins -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/lg-fullscreen/1.2.1/lg-fullscreen.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/lg-thumbnail/1.2.1/lg-thumbnail.min.js"></script>

</head>

```{css}
.column {
  float: left;
  width: 45%;
  margin-left: 1rem;
}

/* Clear floats after the columns */
.row:after {
  content: "";
  display: table;
  clear: both;
}

#lightgallery > a > img:hover {
   transform: scale(1.15, 1.15);
   transition: 0.4s ease-in-out;
   cursor: pointer;
}


/* For some reason, icons are not loaded so I choose them myself */
.lg-actions .lg-next {
  content:"\1433"
}
.lg-actions .lg-prev {
  content:"\1438"
}
.lg-toolbar .lg-download {
 content:"\2913"
}
.lg-toolbar .lg-close {
 content:"\00D7"
}
.lg-toolbar .lg-icon {
	background-color: #000;
	border-color: #000;
	border-style: solid;
}
```


```{r include = FALSE}
source(here::here("R/functions.R"))

# Make list of tidytuesday plots I want to show in the gallery
tt_plots <- rbind(
  c(2022, 47),
  c(2022, 51),
  c(2022, 28),
  c(2022, 09),
  c(2021, 40),
  c(2021, 23),
  c(2021, 17),
  c(2021, 15),
  c(2021, 13),
  c(2021, 12)
)

# Download the plots and create the thumbnails
apply(tt_plots, 1, function(x) get_tt_image(x[1], x[2]))
```

```{r}
# Create layout
withTags(
  div(
    class = "row",
    id = "lightgallery",
    tagList(
      make_gallery_layout()
    )
  )
)

```

<script type="text/javascript">
    lightGallery(document.getElementById('lightgallery'), {
      hideBarsDelay: 1500
    }); 
</script>
