---
title: "Lighthouses in the world"
description: |
  A short description of the post.
author:
  - name: Etienne Bacher
    url: {}
date: 2022-01-29
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(osmdata)
library(sf)
library(rnaturalearth)
library(ggplot2)
library(ggtext)
library(giscoR)

# sysfonts::font_add_google("Montserrat")
```

```{r cache=TRUE}
q <- opq(bbox = c(-180, -90, 180, 90), timeout = 25*100) |>
  add_osm_feature("man_made", "lighthouse")

lighthouse <- osmdata_sf(q)
dim(lighthouse$osm_points)
```

```{r}
# Comes from https://r-spatial.org/r/2018/10/25/ggplot2-sf.html
world <- gisco_countries |> 
  st_transform(crs = "+proj=laea +lat_0=52 +lon_0=10 +x_0=4321000 +y_0=3210000 +ellps=GRS80 +units=m +no_defs")
```

```{r}
ggplot() +
  geom_sf(data = world) +
  geom_sf(
    data = lighthouse$osm_points,
    inherit.aes = FALSE,
    colour = "yellow",
    alpha = 0.5,
    size = 0.1
  ) +
  labs(
    title = "LIGHTHOUSES",
    caption = "Made by Etienne Bacher &middot; Original plot by Dominic Royé &middot; Data from OSM<br>"
  ) +
  theme_void() +
  theme(
    plot.background = element_rect("black"),
    panel.background = element_rect("black"),
    plot.title = element_markdown(color = "yellow", hjust = 0.5, 
                                  # size = 60, vjust = 0
                                  ),
    plot.caption = element_markdown(color = "yellow", hjust = 0.5, 
                                    # size = 20
                                    ),
    text = element_text(family = "Montserrat")
  )
```

```{r}
ggsave("lighthouses.png", width = 8, height = 7)
```

