on:
  push:
    branches: master

name: foo

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master

      - uses: r-lib/actions/setup-pandoc@master

      - name: Install dependencies
        run: |
          install.packages("httr")
        shell: Rscript {0}

      - name: Test
        run: Rscript -e 'httr::GET("https://api.github.com/repos/etiennebacher/tidytuesday/git/trees/master?recursive=1")'
