on:
  push:
    branches: master

name: Render & Deploy Site

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master

      - name: Install dependencies
        run: |
          install.packages("fs")
        shell: Rscript {0}

      - name: Copy redirects in site
        run: |
          fs::file_copy("_redirects", "_site/_redirects")
        shell: Rscript {0}
