on:
  push:
    branches: master

name: Render & Deploy Site

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master

      - uses: r-lib/actions/setup-pandoc@master

      - name: Install dependencies
        run: |
          install.packages(c("rmarkdown", "distill", "postcards", "devtools",
          "fs", "htmltools", "here", "magick", "httr"))
        shell: Rscript {0}

      - name: Render Site
        run: Rscript -e 'rmarkdown::render_site(encoding = "UTF-8")'
      - name: Copy redirects and gallery images
        run: Rscript -e 'fs::file_copy("_redirects", "_site/_redirects"); fs::file_copy("_gallery/img", "_site/_gallery/img")'
      - name: Commit results
        run: |
          git add -A
          git commit -m 'Rebuild site' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
