on:
  push:
    branches: master

name: Render & Deploy Site

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master

      - name: Copy redirects in site
        run: |
          file.copy("_redirects", "_site/_redirects", overwrite = T)
        shell: Rscript {0}
